
public interface CarbonFootprint 
{
	double ELECTRICITY_EMISSIONS_FACTOR = 1.37;
	int MONTHS_IN_YEAR = 12;
	int WEEKS_IN_YEAR = 52;
	double POUNDS_OF_CO2_PER_GALLON = 19.4;
	double EMISSIONS_OTHER_THAN_CO2 = 100 / 95;
	int MEAT_EMISSIONS_FACTOR = 1452;
	int BAKERY_PRODUCT_EMISSIONS_FACTOR = 741;
	int DAIRY_EMISSIONS_FACTOR = 1911;
	int FRUITS_AND_VEGATABLE_EMISSIONS_FACTOR = 1176;
	int EATING_OUT_EMISSIONS_FACTOR = 368;
	int OTHER_FOOD_EMISSIONS_FACTOR = 467;
	double GRAM_TO_POUND_RATE = 0.0022;
	
	
	double getCarbonFootprint();
	String toString();
}
